/*
DROP TABLE DOONG_JI.MEMBER;
DROP TABLE DOONG_JI.GROUP;
DROP TABLE DOONG_JI.BELONGS_TO;
DROP TABLE DOONG_JI.MESSAGE_BOX;
*/

CREATE TABLE DOONG_JI.MEMBER(
Member_num INT(6) NOT NULL AUTO_INCREMENT,
Id VARCHAR(15) NOT NULL ,
Pw VARCHAR(15) NOT NULL,
Name VARCHAR(20) NOT NULL,
CONSTRAINT MEMBER_PK PRIMARY KEY(MEMBER_num)
);

CREATE TABLE DOONG_JI.GROUP(
Group_num INT(6) NOT NULL AUTO_INCREMENT,
Name VARCHAR(20) NOT NULL,
Group_location VARCHAR(30) NOT NULL,
Limit_access INT(5) NULL DEFAULT 500,
CONSTRAINT GROUP_PK PRIMARY KEY(Group_num)
);

CREATE TABLE DOONG_JI.BELONGS_TO(
Member_num INT(6) NOT NULL,
Group_num INT(6) NOT NULL,
CONSTRAINT BELONGS_TO_MEMBER FOREIGN KEY(Member_num) REFERENCES DOONG_JI.MEMBER(Member_num),
CONSTRAINT BELONGS_TO_GROUP FOREIGN KEY(Group_num) REFERENCES DOONG_JI.GROUP(Group_num),
CONSTRAINT BELONGS_TO_PK PRIMARY KEY(MEMBER_num,Group_num));

CREATE TABLE DOONG_JI.MESSAGE_BOX(
Message_num INT(6) NOT NULL AUTO_INCREMENT,
Message_body VARCHAR(100),
Sender INT(6) NOT NULL,
Receiver INT(6) NOT NULL,
CONSTRAINT MESSAGE_BOX_PK PRIMARY KEY(Message_num),
CONSTRAINT MESSAGE_BOX_SEND_FK FOREIGN KEY(Sender) REFERENCES DOONG_JI.MEMBER(Member_num),
CONSTRAINT MESSAGE_BOX_RECV_FK FOREIGN KEY(Receiver) REFERENCES DOONG_JI.MEMBER(Member_num));




