INSERT INTO DOONG_JI.members(User_id, User_pw, User_name) VALUES('test_user1','1234','user1');
INSERT INTO DOONG_JI.members(User_id, User_pw, User_name) VALUES('test_user2','1234','user2');
INSERT INTO DOONG_JI.members(User_id, User_pw, User_name) VALUES('test_user3','1234','user3');
INSERT INTO DOONG_JI.members(User_id, User_pw, User_name) VALUES('test_user4','1234','user4');
INSERT INTO DOONG_JI.members(User_id, User_pw, User_name) VALUES('test_user5','1234','user5');
INSERT INTO DOONG_JI.members(User_id, User_pw, User_name) VALUES('test_user6','1234','user6');
INSERT INTO DOONG_JI.members(User_id, User_pw, User_name) VALUES('test_user7','1234','user7');
INSERT INTO DOONG_JI.members(User_id, User_pw, User_name) VALUES('test_user8','1234','user8');
INSERT INTO DOONG_JI.members(User_id, User_pw, User_name) VALUES('test_user9','1234','user9');
INSERT INTO DOONG_JI.members(User_id, User_pw, User_name) VALUES('test_user10','1234','user10');
INSERT INTO DOONG_JI.members(User_id, User_pw, User_name) VALUES('test_user11','1234','user11');
INSERT INTO DOONG_JI.members(User_id, User_pw, User_name) VALUES('test_user12','1234','user12');
INSERT INTO DOONG_JI.members(User_id, User_pw, User_name) VALUES('test_user13','1234','user13');
INSERT INTO DOONG_JI.members(User_id, User_pw, User_name) VALUES('test_user14','1234','user14');
INSERT INTO DOONG_JI.members(User_id, User_pw, User_name) VALUES('test_user15','1234','user15');
INSERT INTO DOONG_JI.members(User_id, User_pw, User_name) VALUES('test_user16','1234','user16');
INSERT INTO DOONG_JI.members(User_id, User_pw, User_name) VALUES('test_user17','1234','user17');
INSERT INTO DOONG_JI.members(User_id, User_pw, User_name) VALUES('test_user18','1234','user18');
INSERT INTO DOONG_JI.members(User_id, User_pw, User_name) VALUES('test_user19','1234','user19');
INSERT INTO DOONG_JI.members(User_id, User_pw, User_name) VALUES('test_user20','1234','user20');
INSERT INTO DOONG_JI.members(User_id, User_pw, User_name) VALUES('test_user21','1234','user21');
INSERT INTO DOONG_JI.members(User_id, User_pw, User_name) VALUES('test_user22','1234','user22');
INSERT INTO DOONG_JI.members(User_id, User_pw, User_name) VALUES('test_user23','1234','user23');
INSERT INTO DOONG_JI.members(User_id, User_pw, User_name) VALUES('test_user24','1234','user24');
INSERT INTO DOONG_JI.members(User_id, User_pw, User_name) VALUES('test_user25','1234','user25');
INSERT INTO DOONG_JI.members(User_id, User_pw, User_name) VALUES('test_user26','1234','user26');
INSERT INTO DOONG_JI.members(User_id, User_pw, User_name) VALUES('test_user27','1234','user27');
INSERT INTO DOONG_JI.members(User_id, User_pw, User_name) VALUES('test_user28','1234','user28');
INSERT INTO DOONG_JI.members(User_id, User_pw, User_name) VALUES('test_user29','1234','user29');
INSERT INTO DOONG_JI.members(User_id, User_pw, User_name) VALUES('test_user30','1234','user30');

INSERT INTO DOONG_JI.locations(X_pos, Y_pos) VALUES('0','0');
INSERT INTO DOONG_JI.locations(X_pos, Y_pos) VALUES('1','1');
INSERT INTO DOONG_JI.locations(X_pos, Y_pos) VALUES('2','2');
INSERT INTO DOONG_JI.locations(X_pos, Y_pos) VALUES('3','3');
INSERT INTO DOONG_JI.locations(X_pos, Y_pos) VALUES('4','4');

INSERT INTO DOONG_JI.groups(Grp_name,Grp_loc,Grp_radius) VALUES('test_groups1',1,500);
INSERT INTO DOONG_JI.groups(Grp_name,Grp_loc,Grp_radius) VALUES('test_groups2',2,1000);
INSERT INTO DOONG_JI.groups(Grp_name,Grp_loc,Grp_radius) VALUES('test_groups3',3,500);
INSERT INTO DOONG_JI.groups(Grp_name,Grp_loc,Grp_radius) VALUES('test_groups4',4,2000);
INSERT INTO DOONG_JI.groups(Grp_name,Grp_loc,Grp_radius) VALUES('test_groups5',5,1500);
INSERT INTO DOONG_JI.groups(Grp_name,Grp_loc,Grp_radius) VALUES('test_groups6',1,2500);



INSERT INTO DOONG_JI.belongs_tos(Mem_id, Grp_id) VALUES(1,1);
INSERT INTO DOONG_JI.belongs_tos(Mem_id, Grp_id) VALUES(1,2);
INSERT INTO DOONG_JI.belongs_tos(Mem_id, Grp_id) VALUES(1,5);
INSERT INTO DOONG_JI.belongs_tos(Mem_id, Grp_id) VALUES(2,1);
INSERT INTO DOONG_JI.belongs_tos(Mem_id, Grp_id) VALUES(3,2);
INSERT INTO DOONG_JI.belongs_tos(Mem_id, Grp_id) VALUES(4,3);
INSERT INTO DOONG_JI.belongs_tos(Mem_id, Grp_id) VALUES(5,5);
INSERT INTO DOONG_JI.belongs_tos(Mem_id, Grp_id) VALUES(5,6);
INSERT INTO DOONG_JI.belongs_tos(Mem_id, Grp_id) VALUES(5,1);
INSERT INTO DOONG_JI.belongs_tos(Mem_id, Grp_id) VALUES(6,6);
INSERT INTO DOONG_JI.belongs_tos(Mem_id, Grp_id) VALUES(7,1);
INSERT INTO DOONG_JI.belongs_tos(Mem_id, Grp_id) VALUES(8,2);
INSERT INTO DOONG_JI.belongs_tos(Mem_id, Grp_id) VALUES(9,3);
INSERT INTO DOONG_JI.belongs_tos(Mem_id, Grp_id) VALUES(10,4);
INSERT INTO DOONG_JI.belongs_tos(Mem_id, Grp_id) VALUES(11,5);
INSERT INTO DOONG_JI.belongs_tos(Mem_id, Grp_id) VALUES(12,6);
INSERT INTO DOONG_JI.belongs_tos(Mem_id, Grp_id) VALUES(13,1);
INSERT INTO DOONG_JI.belongs_tos(Mem_id, Grp_id) VALUES(13,2);
INSERT INTO DOONG_JI.belongs_tos(Mem_id, Grp_id) VALUES(13,3);
INSERT INTO DOONG_JI.belongs_tos(Mem_id, Grp_id) VALUES(13,4);
INSERT INTO DOONG_JI.belongs_tos(Mem_id, Grp_id) VALUES(14,2);
INSERT INTO DOONG_JI.belongs_tos(Mem_id, Grp_id) VALUES(15,3);
INSERT INTO DOONG_JI.belongs_tos(Mem_id, Grp_id) VALUES(16,2);
INSERT INTO DOONG_JI.belongs_tos(Mem_id, Grp_id) VALUES(17,4);
INSERT INTO DOONG_JI.belongs_tos(Mem_id, Grp_id) VALUES(18,5);
INSERT INTO DOONG_JI.belongs_tos(Mem_id, Grp_id) VALUES(19,1);
INSERT INTO DOONG_JI.belongs_tos(Mem_id, Grp_id) VALUES(19,3);
INSERT INTO DOONG_JI.belongs_tos(Mem_id, Grp_id) VALUES(19,4);
INSERT INTO DOONG_JI.belongs_tos(Mem_id, Grp_id) VALUES(19,6);
INSERT INTO DOONG_JI.belongs_tos(Mem_id, Grp_id) VALUES(20,1);
INSERT INTO DOONG_JI.belongs_tos(Mem_id, Grp_id) VALUES(21,2);
INSERT INTO DOONG_JI.belongs_tos(Mem_id, Grp_id) VALUES(22,1);
INSERT INTO DOONG_JI.belongs_tos(Mem_id, Grp_id) VALUES(23,1);
INSERT INTO DOONG_JI.belongs_tos(Mem_id, Grp_id) VALUES(23,2);
INSERT INTO DOONG_JI.belongs_tos(Mem_id, Grp_id) VALUES(23,5);
INSERT INTO DOONG_JI.belongs_tos(Mem_id, Grp_id) VALUES(24,6);
INSERT INTO DOONG_JI.belongs_tos(Mem_id, Grp_id) VALUES(25,2);
INSERT INTO DOONG_JI.belongs_tos(Mem_id, Grp_id) VALUES(26,3);
INSERT INTO DOONG_JI.belongs_tos(Mem_id, Grp_id) VALUES(26,4);
INSERT INTO DOONG_JI.belongs_tos(Mem_id, Grp_id) VALUES(26,6);
INSERT INTO DOONG_JI.belongs_tos(Mem_id, Grp_id) VALUES(27,3);
INSERT INTO DOONG_JI.belongs_tos(Mem_id, Grp_id) VALUES(28,4);
INSERT INTO DOONG_JI.belongs_tos(Mem_id, Grp_id) VALUES(29,2);
INSERT INTO DOONG_JI.belongs_tos(Mem_id, Grp_id) VALUES(29,3);
INSERT INTO DOONG_JI.belongs_tos(Mem_id, Grp_id) VALUES(29,5);
INSERT INTO DOONG_JI.belongs_tos(Mem_id, Grp_id) VALUES(30,5);
commit;


/*INSERT INTO DOONG_JI.locations(X_pos, Y_pos) VALUES('','');
INSERT INTO DOONG_JI.groups(Grp_name,Grp_loc,Grp_radius) VALUES('','','');
INSERT INTO DOONG_JI.belongs_tos(Mem_id, Grp_id) VALUES('','','');
INSERT INTO DOONG_JI.message_boxes(Msg_body, Msg_sender, Msg_receiver) VALUES('', '', '');
*/
